spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      location: C:/upload
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:h2:tcp://localhost/~/musinsa
    driver-class-name: org.h2.Driver
    username: sa
    password: sa


  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행시점에 내가 가지고 있는 테이블 제거(drop) 후 다시 생성
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        user_sql_comments: false
  open-in-view: false

logging: # 로거를 통해 로그 출력
  level:
    org.hibernate.SQL: debug # 로거를 통해 hibernate 실행 SQL을 남긴다.
    spring:
      mvc:
        static-path-pattern=/webapp/**:
